packages:
  common:
    - 'jq' 
    - 'fzf' 
    - 'neomutt' 
    - 'w3m'
    - 'tmux'
    - 'vim'
    - 'zsh'
  darwin:
    brews:
    - 'git'
    - 'newsboat'
    - 'ghostty'
    casks:
    - 'alacritty'
    - 'emacs'
    - 'font-zed-mono-nerd-font'
    - 'bitwarden'
  linux:
    snaps:
      - 'firefox'
      - 'bitwarden'
      - 'ghostty'
    apt:
      - 'wl-clipboard'
      - 'emacs' 
      - 'alacritty'
      - 'libfuse2'    # Required for AppImage
      - 'zlib1g-dev'  # Required for AppImage
