set nocompatible	" be iMproved, required
filetype off		" required

" https://stackoverflow.com/questions/23012391/how-and-where-is-my-viminfo-option-set
set viminfo=%,<800,'10,/50,:100,h,f0,n~/.vim/cache/.viminfo

if &shell =~# 'fish$'
    set shell=sh
endif

" vim-plug

" Run PlugInstall if there are missing plugins
autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
  \| PlugInstall --sync | source $MYVIMRC
\| endif

call plug#begin('~/.vim/bundle')
" Syntax highlighting for chezmoi files
Plug 'alker0/chezmoi.vim'

Plug 'tpope/vim-fugitive'
Plug 'balanceiskey/vim-framer-syntax'
Plug 'tpope/vim-sensible'
Plug 'junegunn/fzf'
"
" Colour Schemes
Plug 'dracula/vim', { 'as': 'dracula' }
Plug 'NLKNguyen/papercolor-theme'
" Plugin 'oceanic-next'
Plug 'joshdick/onedark.vim'
" Plugin 'nord-vim'
Plug 'drewtempelmeyer/palenight.vim'
" Plugin 'quantum.vim'
" Plugin 'ayu-vim'
Plug 'ayu-theme/ayu-vim'
Plug 'catppuccin/vim', { 'as': 'catppuccin' }

call plug#end()

" The first [ is entered with CTRL+V,ESC
set t_8f=[38;2;%lu;%lu;%lum
set t_8b=[48;2;%lu;%lu;%lum

set termguicolors
" set background=[light|dark]
" colorscheme command

" https://github.com/NLKNguyen/papercolor-theme
set background=dark
" colorscheme PaperColor
" colorscheme OceanicNext
" colorscheme onedark
" colorscheme nord
" let ayucolor="light"  " for light version of theme
" let ayucolor="mirage" " for mirage version of theme
let ayucolor="dark"   " for dark version of theme
" colorscheme ayu
" color vim-framer-syntax
colorscheme catppuccin_mocha

" Mouse scrolling in all modes (scrolls vim in tmux windows)
set mouse=a

" Dont automatically insert comment
" from http://vim.wikia.com/wiki/Disable_automatic_comment_insertion
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=let
